# Generated by Django 5.1.5 on 2025-02-08 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_category_options_book_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='owned_books', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(auto_now_add=True)),
                ('rental_duration', models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (9, '9 Months')], default=1)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='website.book')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
