# Generated by Django 5.1.5 on 2025-02-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_book_owner_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price_per_day',
            new_name='price',
        ),
        migrations.AddField(
            model_name='rental',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
